### ISSUE TITLE
dpi not doing its job and not changing anything

### ISSUE THREAD

**Issue by itzRealDuck** [Gwynsav/gwdawful#4]

**Comment by itzRealDuck** [comment]
user.dpi i meant lol

**Comment by Gwynsav** [comment]
Seems like I deleted the line for `theme/init.lua` where it would set the DPI accordingly when I did the refactor and somehow didn't notice. I'll add it back whenever soon I when I find the time.

**Comment by Gwynsav** [comment]
Readded the code that makes `user.dpi` actually do something, tested a bit to confirm that it works. So addressed in [`7a966e5`](https://github.com/Gwynsav/gwdawful/commit/7a966e5e641ed772304b3b4aceddf0235a052944).

**Comment by itzRealDuck** [comment]
k ty
